replicaCount: 1

image:
  repository: 544277935543.dkr.ecr.us-west-2.amazonaws.com/oauth4os
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8443

ingress:
  enabled: false
  className: nginx
  host: oauth4os.example.com
  tls: []

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 128m
    memory: 256Mi

config:
  upstream:
    engine: http://opensearch:9200
    dashboards: http://opensearch-dashboards:5601
  listen: ":8443"
  providers: []
  scope_mapping: {}

env: []
#  - name: AWS_REGION
#    value: us-west-2

nodeSelector: {}
tolerations: []
