global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: oauth4os
    static_configs:
      - targets: ['oauth-proxy:8443']
    metrics_path: /metrics
    scheme: http
